package com.aws.omm.domain.customerorder;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StoreMasterDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.util.List<com.aws.omm.domain.customerorder.Store> storeDetails;

    public StoreMasterDetails() {
    }

    public java.util.List<com.aws.omm.domain.customerorder.Store> getStoreDetails() {
        return this.storeDetails;
    }

    public void setStoreDetails(
            java.util.List<com.aws.omm.domain.customerorder.Store> storeDetails) {
        this.storeDetails = storeDetails;
    }

    public StoreMasterDetails(
            java.util.List<com.aws.omm.domain.customerorder.Store> storeDetails) {
        this.storeDetails = storeDetails;
    }

    @Override
    public String toString() {
        return "StoreMasterDetails " +
                "storeDetails=" + storeDetails ;
    }
}